name: shaped_bottom_bar
description: Fully customizable bottom navigation bar with multiple built-in shapes and support custom shapes also with built-in transition animations
version: 1.1.0
homepage: https://github.com/koukibadr/Shaped-Bottom-Bar

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.4

flutter:

